# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: LeafLook
email: novaldypratama@mail.ugm.ac.id
description: >
  A web app for plant disease identification through image processing is an innovative solution
  that can assist farmers and agricultural experts in identifying crop diseases quickly and accurately.
  Users can upload images of diseased plants and receive immediate feedback on the type of disease affecting the crops.
  LeafLook uses machine learning algorithms and computer vision techniques to analyze the images and make accurate predictions.
  With the ability to analyze large quantities of data quickly and accurately, the web app can help farmers to save time and money 
  by preventing the spread of disease and ensuring that crops are healthy and productive. Overall, this technology has the potential 
  to revolutionize the agriculture industry.
baseurl: "/LeafLook" # the subpath of your site, e.g. /blog
url: "https://leaflook.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
